### PR TITLE
Silent swordmaiden xivdeck plugin

### PR DESCRIPTION
**Pull request by SilentSwordmaiden**
### Checks
- [x] I tested my changes or release
- [x] I agree to the [terms of service](https://streamcontroller.github.io/docs/latest/plugin_dev/submitting/terms/)

I know tested everything twice again and fixed every issue I noticed. Except the requirements.txt-part from the last PR.

>  I didn't test the requirements.txt, since I read it as only working when it's installed from the store?
>
> I had to manually add "websockets" into the flatpak because of that.

Is there anything I still can/should do?

### CODE REVIEW

**Comment by Core447** [comment]
Great work!
I opened a [PR](https://github.com/SilentSwordmaiden/StreamController-XIVDeck-Plugin/pull/3) to fix some things with the requirements. You can test the installation of your plugin by using the "custom plugins" feature in the app settings.

**Comment by SilentSwordmaiden** [comment]
I removed my changes from the flatpack and it installed correctly. Should be working now,

**Comment by Core447** [comment]
Seems like I forgot to add `pillow` to the requirements, sorry. Can you please add it? Two other things I noticed:
- The new versions (with Stream Deck Plus support) show your actions as possibly incompatible, to solve this (you don't have to) you have to add [this](https://github.com/StreamController/OSPlugin/blob/9ebf9a89063a06c776346598e9181835d78534e2/main.py#L60-L62). This still needs to be added to the wiki
- Please add descriptions to your manifest, you can have a look at [this one](https://github.com/StreamController/OSPlugin/blob/main/manifest.json) as a reference.

**Comment by SilentSwordmaiden** [comment]
I hope this does the trick now?

**Comment by Core447** [comment]
Yep, thanks! And sorry for the inconvenience!

**Comment by Core447** [comment]
Sorry, I missed that the PR was for the `main` branch. The current app version is using the `1.5.0.beta.5` branch. I just applied the changes manually. Again, sorry for the inconveniences!

**Pull request merged**
