### PR TITLE
Added AudioControl Plugin to the store

### PR DESCRIPTION
**Pull request by G4PLS**
For the current small plugin that lets you change the actual Volumes of a specified device.
The [Audio Control](https://github.com/G4PLS/AudioControl) Plugin.

The Volume Display is currently being Developed and should later Display the current Volume of a Device.

### CODE REVIEW

**Comment by Core447** [comment]
Nice work! Some things I noticed:
- You're importing `ScaleRow` from `GtkHelper` but it doesn't have `ScaleRow`. Feel free to open a PR for it. However, for backward compatibility it might be useful to add the class to the plugin itself.
- The labels are not localized (you don't have to do that right now) (maybe just add `en_US` so that others can translate it later). checkout [Localization](https://streamcontroller.github.io/docs/latest/plugin_dev/modify_template/localization/)
- Maybe change the import of the action in `main.py` to:
  ```
  from .actions.VolumeAdjust import VolumeAdjust
  from .actions.SetVolume import SetVolume
  from .actions.VolumeDisplay import VolumeDisplay
  ```
  This way IDEs can find the actions no matter where the plugin is stored
  
 Again, great work! This will be the first "third party" plugin!

**Comment by Core447** [comment]
> Is it possible to provide 2 versions of the Plugin?
> One with some backwards compatibility and one where GtkHelper got extended with the ScaleRow?

No, not at the moment, but when we bump the version to `2.x.x` you can ship a version of your plugin without the `ScaleRow` class.

**Comment by G4PLS** [comment]
> > Is it possible to provide 2 versions of the Plugin?
> > One with some backwards compatibility and one where GtkHelper got extended with the ScaleRow?
> 
> No, not at the moment, but when we bump the version to `2.x.x` you can ship a version of your plugin without the `ScaleRow` class.
> 
> Edit: StreamController always installs the latest version of a plugin with a matching major version

Plugin and commit hash got updated. Now includes localization for en_US and de_DE

Plugin now checks if the GtkHelper can import ScaleRow and uses the internal ScaleRow as a fallback

**Comment by Core447** [comment]
I opened a [PR](https://github.com/G4PLS/AudioControl/pull/1) to your repo.

**Comment by G4PLS** [comment]
Everything is merged and Commit Hash is updated!

**Pull request merged**
