### PR TITLE
Add OBS LiveSplit One plugin

### PR DESCRIPTION
**Pull request by pniedzielski**
This PR adds a plugin to control the LiveSplit One source plugin for OBS using the OBS websocket interface.
Currently, you can split, undo and skip splits, change your timing comparison and timing method, and reset your attempt.

### Checks
- [X] I tested my changes or release
- [X] I agree to the [terms of service](https://streamcontroller.github.io/docs/latest/plugin_dev/submitting/terms/)

I tested against the current `main` of StreamController in a flatpak build.

### CODE REVIEW

**Comment by Core447** [comment]
The current app version uses the 1.5.0.beta.5 branch. Can you please open a new PR to this branch?

**Comment by pniedzielski** [comment]
@Core447 I've changed the base branch of this PR to `1.50.beta.5` and also force-pushed so my branch targets that version.  It should be ready for review now.

**Comment by Core447** [comment]
Yes, that works! Thanks, and amazing work! Are you on the [Discord](https://discord.gg/MSyHM8TN3u) so that I can mention you in the release message?

**Comment by pniedzielski** [comment]
I did join the Discord, I'm @debianchan there.

**Pull request merged**
