### PR TITLE
Add Tabler.io iconpack

### PR DESCRIPTION
**Pull request by fishgrind**
Added tabler icons for store.

### Checks
- [x] I tested my changes or release
- [x] I agree to the [terms of service](https://streamcontroller.github.io/docs/latest/plugin_dev/submitting/terms/)

### CODE REVIEW

**Comment by Core447** [comment]
Great work, thank you! Could you please add an alpha channel to your `store/Thumbnail.png`? The current app version has a bug that won't show the thumbnail if it hasn't one. Sorry for the inconvenience.

**Comment by fishgrind** [comment]
> Great work, thank you! Could you please add an alpha channel to your `store/Thumbnail.png`? The current app version has a bug that won't show the thumbnail if it hasn't one. Sorry for the inconvenience.

Sure, i'll do that and update it and let you know when i did!

Colin

**Comment by fishgrind** [comment]
Hey @Core447 

I have updated my repo, the Thumbnail.png now has an alpha channel.

**Comment by Core447** [comment]
Perfect, great work, thank you!

**Pull request merged**
