### PR TITLE
Add discord plugin

### PR DESCRIPTION
**Pull request by ImDevinC**
### Checks
- [x] I tested my changes or release
- [x] I agree to the [terms of service](https://streamcontroller.github.io/docs/latest/plugin_dev/submitting/terms/)

### CODE REVIEW

**Comment by Core447** [comment]
Some things I noticed:
1. The thumbnail doesn't seem to load in the store. Can you maybe try to change it to a png with transparent layer?
2. When I add a "Mute" action directly after the installation (so without any config), I get this:
  ```
  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 1435, in own_actions_update
      action.on_update()
    File "/app/bin/StreamController/src/backend/PluginManager/ActionBase.py", line 129, in on_update
      self.on_ready() # backward compatibility
      ^^^^^^^^^^^^^^^
    File "/home/core447/Documents/StreamController-config/plugins/com_imdevinc_StreamControllerDiscordPlugin/actions/MuteAction.py", line 20, in on_ready
      self.plugin_base.backend.register_callback(
    File "/app/lib/python3.11/site-packages/rpyc/core/netref.py", line 239, in __call__
      return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/lib/python3.11/site-packages/rpyc/core/netref.py", line 63, in syncreq
      return conn.sync_request(handler, proxy, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/lib/python3.11/site-packages/rpyc/core/protocol.py", line 744, in sync_request
      return _async_res.value
             ^^^^^^^^^^^^^^^^
    File "/app/lib/python3.11/site-packages/rpyc/core/async_.py", line 111, in value
      raise self._obj
  _get_exception_class.<locals>.Derived: 'NoneType' object has no attribute 'subscribe'
  
  ========= Remote Traceback (1) =========
  Traceback (most recent call last):
    File "/app/lib/python3.11/site-packages/rpyc/core/protocol.py", line 369, in _dispatch_request
      res = self._HANDLERS[handler](self, *args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/lib/python3.11/site-packages/rpyc/core/protocol.py", line 863, in _handle_call
      return obj(*args, **dict(kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/core447/Documents/StreamController-config/plugins/com_imdevinc_StreamControllerDiscordPlugin/backend.py", line 62, in register_callback
      self.discord_client.subscribe(key)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'subscribe'
  ```
3. It would be nice to also show the `failed to setup discord client: Error, could not find Discord. is Discord running?` error in the ui

**Comment by ImDevinC** [comment]
@Core447 thanks for the validation. Updated accordingly in this latest release

**Comment by Core447** [comment]
I still have the problem with the missing thumbnail. [This PR](https://github.com/ImDevinC/StreamControllerDiscordPlugin/pull/8) should fix this.

**Comment by ImDevinC** [comment]
Updated, thanks for the PR!

**Pull request merged**
